const images ={
    backgroundheader: require("./backgroundheader.png"),
    salad: require("./salad.jpg"),
    login:require("./login.jpg"),
    googleicon: require("./google.png"),
    facebookicon: require("../img/facebook.png"),
    appleicon:require("../img/apple-logo.png"),
    menu:require("../img/menu.png"),
    bg1: require("../img/Frame1.png"),
    bg2: require("../img/frame2.png"),
    bg3: require("../img/bg3.png"),
    soda: require("../img/soda.png"),
    miso: require("../img/miso.png"),
    sushi: require("../img/sushi.png"),
    teaframe: require ("../img/tea.png"),
    sushiframe: require ("../img/sushiframe.png"),
    check: require ("../img/check.png"),
    icon: require ("../img/iconnn.png"),
}
export default images;